### ISSUE TITLE
Lack of AoT support

### ISSUE THREAD

**Issue by bvasilenko** [surol/ng2-forms-extra#1]
The command I am using is:
ng build --prod --aot --environment prod --no-progress

And here's an error I am getting:
ERROR in Unexpected value 'FormsExtraModule in node_modules/ng2-forms-extra/index.d.ts' imported by the module 'MyAppModule in my-app.module.ts'. Please add a @NgModule annotation.

Could you please make the NPM package compatible with angular/compiler-cli (Ahead of Time compilation)?

Here's a good guide by the way:
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad

**Comment by surol** [comment]
Please try out the `0.4.0-dev` version currently in `devel` branch.

**Comment by surol** [comment]
@bvasilenko The update is published under the `dev` tag. You can try it out by issuing `yarn add ng2-forms-extra@0.4.0-dev` or `npm install ng2-forms-extra@0.4.0-dev`

**Comment by bvasilenko** [comment]
@surol Now it is working with AoT! Big thanks for the fix!

**Comment by surol** [comment]
Fixed in release 0.4.0
